pipeline:
  build:
    image: node:6.9
    commands:
      - sleep 10
      - npm install
      - npm run --silent build || true
      - npm run ci

services:
  redis:
    image: redis:alpine
  rabbit:
    image: rabbitmq:alpine
  gateway:
    image: ecsdevops/aurora-gateway
    entrypoint: /bin/bash
    command:
      - -c
      - sleep 5 && npm run ci
  manager:
    image: ecsdevops/aurora-manager
    entrypoint: /bin/bash
    command:
      - -c
      - sleep 8 && npm run ci
